name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python.3.9.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('dev.requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.requirements.txt
      - name: Check format
        run: |
          ./bin/format
      - name: Check typing
        run: |
          ./bin/lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
